AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda EC2 Scheduler

Parameters:
  MemorySize:
    Description: Memory size of Lambda function.
    Type: Number
    Default: 1024
  Schedule:
    Description: Schedule for how often to run lambda-ec2-operator function. CWE Scheduled Expression or Cron format
    Type: String
    Default: rate(5 minutes)
  S3Bucket:
    Description: Name of S3 bucket that contains source code of your Lambda function. e.g. source-us-west-2
    Type: String
  S3Key:
    Description: Location and name of .zip file that contains your source code. e.g. solutions/scheduler-lambda-function.zip
    Type: String
    
Resources:
  ec2SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ec2SchedulerPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:  arn:aws:logs:*:*:log-group:/aws/lambda/*
              - Effect: Allow
                Action:
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:DescribeRegions
                  - ec2:DescribeInstances
                  - lambda:InvokeFunction
                  - cloudformation:DescribeStacks
                Resource: "*"
  ec2Scheduler:
    Type: AWS::Lambda::Function
    Properties:
      Description: EC2 Scheduler Lambda function
      Handler: lambda-ec2-scheduler.lambda_handler
      MemorySize:
        Ref: MemorySize
      Role:
        Fn::GetAtt:
          - ec2SchedulerRole
          - Arn
      Code:
        S3Bucket:
          Ref: S3Bucket
        S3Key:
          Ref: S3Key
      Runtime: python2.7
      Timeout: 60
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to trigger lambda-ec2-scheduler function on CRON scheduler
      ScheduleExpression:
        Ref: Schedule
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - ec2Scheduler
              - Arn
          Id: TargetFunctionV1
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ec2Scheduler
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - ScheduledRule
          - Arn
